CONFIG_NANOPB=y
# Local modules
CONFIG_PROTORPC=y
CONFIG_PBGENERIC=y
CONFIG_TESTRPC=y
CONFIG_SYSTEMRPC=y
CONFIG_RTOSUTILS_RPC=y

# Logging
CONFIG_PBGENERIC_LOG_LEVEL_INF=y
CONFIG_PROTORPC_LOG_LEVEL_INF=y
CONFIG_TESTRPC_LOG_LEVEL_INF=y
CONFIG_SYSTEMRPC_LOG_LEVEL_INF=y
CONFIG_TCPSOCKET_LOG_LEVEL_INF=y
CONFIG_TCPSERVER_LOG_LEVEL_INF=y
