CONFIG_WIFI=y
CONFIG_NET_L2_WIFI_MGMT=y
CONFIG_NVPARMS=y
CONFIG_NVPARMS_LOG_LEVEL_INF=y
#CONFIG_NET_DHCPV4=y

CONFIG_WIFICONNECT=y

# Ram optimizations
# Default 10 (1.6KB each)
CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM=5
# Default 32 (try 8-16)
CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM=15
# Default 5 (try 2-3)
CONFIG_ESP32_WIFI_RX_MGMT_BUF_NUM_DEF=3
# Default y, trades 10K for speed
CONFIG_ESP32_WIFI_IRAM_OPT=n
# Not needed for sensor application (low throughput).
CONFIG_ESP32_WIFI_AMPDU_TX_ENABLED=n
CONFIG_ESP32_WIFI_AMPDU_RX_ENABLED=n

#Logging
CONFIG_WIFICONNECT_LOG_LEVEL_INF=y
CONFIG_NET_L2_WIFI_MGMT_LOG_LEVEL_INF=y
CONFIG_WIFI_LOG_LEVEL_INF=y
