CONFIG_TRACEMODULE=y

# Enable individual trace modules.
CONFIG_PROTORPC_TRACE_MODULE=y

# Define TraceModule ID's.
CONFIG_PROTORPC_TRACE_MODULE_ID=1

# Define TraceModule levels.
CONFIG_PROTORPC_TRACE_MODULE_LEVEL=4
